# HOST/PORT config
addr: localhost:8000

# CORS config
CORS: ["localhost", "genshinbanpick.com", ""]


# Redis config
redis_addr: localhost:6379
redis_pwd: ""
redis_db: 0

# Response message configuration
text_messages:

  # Error message

  ## Connection Error
  params_required: "Param %s is required to connect to the game"
  redis_error: "Redis connection error!!!"
  redis_data_error: "Error data from redis"

  ## Game Error
  player_not_connected: "The other player are not connected yet! You can't not submit your move!!!"
  enough_player: "There are already 2 players in this game. Cannot join!!!"
  not_your_turn: "It is not your turn yet!!!"
  invalid_data_type: "You have submitted the wrong data type for your move"
  wrong_move: "Wrong move!!!"
  data_input_error: "Data Input Error!!!"


  # INFO message
  waiting_player: "The game is created, waiting for the other player to connect.."
  game_ready: "Both player are connected, the game is ready"
  game_ended: "The game has ended!!!"
  game_state_update: "New game state --> Update!!"


# Game format
GAME_TURN_FORMAT:
  1:
    pick: false
    player: 1
  2:
    pick: false
    player: 2
  3:
    pick: false
    player: 1
  4:
    pick: false
    player: 2
  5:
    pick: false
    player: 1
  6:
    pick: false
    player: 2
  7:
    pick: true
    player: 1
  8:
    pick: true
    player: 2
  9:
    pick: true
    player: 2
  10:
    pick: true
    player: 1
  11:
    pick: true
    player: 1
  12:
    pick: true
    player: 2
  13:
    pick: true
    player: 2
  14:
    pick: true
    player: 1
  15:
    pick: false
    player: 1
  16:
    pick: false
    player: 2
  17:
    pick: true
    player: 2
  18:
    pick: true
    player: 1
  19:
    pick: true
    player: 1
  20:
    pick: true
    player: 2
  21:
    pick: true
    player: 2
  22:
    pick: true
    player: 1
  23:
    pick: true
    player: 1
  24:
    pick: true
    player: 2


# Game Config
TURN_EXP: 30